version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medicine-backend
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/medicine
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    network_mode: host

volumes:
  mongo_data: